# Generated by Django 4.0.2 on 2023-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Project_Desc',
            field=models.TextField(default=''),
        ),
    ]
