# Generated by Django 4.0.2 on 2023-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projects_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Project_Link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
