# Generated by Django 4.0.2 on 2023-01-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
