# Generated by Django 4.1.6 on 2023-04-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_project_link_projects_project_live_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_name', models.CharField(max_length=50)),
                ('cer_org', models.CharField(max_length=50)),
                ('cer_details', models.CharField(max_length=200)),
                ('cer_img', models.ImageField(upload_to='certifications')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='Project_Type',
            field=models.CharField(choices=[('SQL', 'SQL'), ('PYTHON', 'PYTHON'), ('DATA_VISUALIZATION', 'DATA_VISUALIZATION')], max_length=50),
        ),
    ]
